export const listings = [{
  title: "Cozy Apartment in Downtown",
  owner: "609c58d74f4e123456789abc", // ObjectId of the owner in your User model
  picturePath: ["path/to/image1.jpg", "path/to/image2.jpg"],
  category: "Apartment",
  price: 1200,
  location: "Downtown",
  reviews: {
    rating: 4.5,
    comments: ["Great place!", "Convenient location."],
  },
  seating: 4,
  description: "A cozy apartment located in the heart of downtown.",
  term: "Long term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 500,
  neighborhood: "Central Square",
  squareFeet: 800,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Spacious House with Garden",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image3.jpg", "path/to/image4.jpg"],
  category: "House",
  price: 2500,
  location: "Suburb",
  reviews: {
    rating: 4.8,
    comments: ["Amazing garden!", "Perfect for families."],
  },
  seating: 6,
  description: "A spacious house with a beautiful garden.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 800,
  neighborhood: "Greenwood",
  squareFeet: 2000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Modern Loft in Arts District",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image5.jpg", "path/to/image6.jpg"],
  category: "Loft",
  price: 1800,
  location: "Arts District",
  reviews: {
    rating: 4.2,
    comments: ["Stylish interior!", "Close to galleries and cafes."],
  },
  seating: 2,
  description: "A modern loft with an artistic vibe in the heart of the arts district.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 650,
  neighborhood: "Gallery Row",
  squareFeet: 1000,
  hasParking: false,
  hasPublicTransportation: true,
},
{
  title: "Luxury Condo with Panoramic Views",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image7.jpg", "path/to/image8.jpg"],
  category: "Condo",
  price: 3500,
  location: "City Center",
  reviews: {
    rating: 4.9,
    comments: ["Incredible views!", "Top-notch amenities."],
  },
  seating: 4,
  description: "A luxurious condo with breathtaking views of the city skyline.",
  term: "Long term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1000,
  neighborhood: "Skyline Heights",
  squareFeet: 1500,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Charming Studio in Historic Building",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image9.jpg", "path/to/image10.jpg"],
  category: "Studio",
  price: 900,
  location: "Old Town",
  reviews: {
    rating: 4.3,
    comments: ["Quaint and cozy!", "Close to shops and restaurants."],
  },
  seating: 2,
  description: "A charming studio apartment located in a historic building.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 450,
  neighborhood: "Historic District",
  squareFeet: 600,
  hasParking: false,
  hasPublicTransportation: true,
},
{
  title: "Sunny Penthouse with Private Terrace",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image11.jpg", "path/to/image12.jpg"],
  category: "Penthouse",
  price: 5000,
  location: "Waterfront",
  reviews: {
    rating: 4.7,
    comments: ["Stunning views!", "Great for entertaining."],
  },
  seating: 8,
  description: "A luxurious penthouse with a sunny terrace overlooking the waterfront.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1200,
  neighborhood: "Harbor District",
  squareFeet: 2500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Secluded Cabin in the Woods",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image13.jpg", "path/to/image14.jpg"],
  category: "Cabin",
  price: 1500,
  location: "Forest",
  reviews: {
    rating: 4.6,
    comments: ["Peaceful getaway!", "Surrounded by nature."],
  },
  seating: 4,
  description: "A cozy cabin nestled in the woods for a serene retreat.",
  term: "Short term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 700,
  neighborhood: "Woodland Valley",
  squareFeet: 1200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Beachfront Villa with Infinity Pool",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image15.jpg", "path/to/image16.jpg"],
  category: "Villa",
  price: 5000,
  location: "Beach",
  reviews: {
    rating: 4.9,
    comments: ["Paradise on earth!", "Unforgettable experience."],
  },
  seating: 10,
  description: "A luxurious beachfront villa with a stunning infinity pool.",
  term: "Long term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Oceanfront",
  squareFeet: 3500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Rustic Farmhouse Retreat",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image17.jpg", "path/to/image18.jpg"],
  category: "Farmhouse",
  price: 2000,
  location: "Countryside",
  reviews: {
    rating: 4.7,
    comments: ["Idyllic setting!", "Perfect for a family getaway."],
  },
  seating: 8,
  description: "A charming farmhouse retreat surrounded by rolling hills and farmland.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 900,
  neighborhood: "Rural Haven",
  squareFeet: 2500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Mountain Chalet with Hot Tub",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image19.jpg", "path/to/image20.jpg"],
  category: "Chalet",
  price: 3000,
  location: "Mountains",
  reviews: {
    rating: 4.8,
    comments: ["Breathtaking views!", "Relaxing getaway."],
  },
  seating: 6,
  description: "A cozy mountain chalet with a private hot tub and panoramic views.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1100,
  neighborhood: "Alpine Ridge",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Urban Penthouse with City Views",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image21.jpg", "path/to/image22.jpg"],
  category: "Penthouse",
  price: 4000,
  location: "City Center",
  reviews: {
    rating: 4.9,
    comments: ["Spectacular skyline!", "Luxurious amenities."],
  },
  seating: 8,
  description: "A stylish penthouse apartment with stunning city views and modern design.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1300,
  neighborhood: "Downtown District",
  squareFeet: 2200,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Lakefront Cottage with Private Dock",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image23.jpg", "path/to/image24.jpg"],
  category: "Cottage",
  price: 1800,
  location: "Lakefront",
  reviews: {
    rating: 4.7,
    comments: ["Peaceful retreat!", "Great fishing spot."],
  },
  seating: 4,
  description: "A charming cottage nestled on the shores of a serene lake, complete with a private dock.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: true,
  impressions: 900,
  neighborhood: "Lakeside Haven",
  squareFeet: 1200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Historic Townhouse in Old City",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image25.jpg", "path/to/image26.jpg"],
  category: "Townhouse",
  price: 2800,
  location: "Historic District",
  reviews: {
    rating: 4.6,
    comments: ["Charming ambiance!", "Close to attractions."],
  },
  seating: 6,
  description: "A beautifully restored historic townhouse in the heart of the old city.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1000,
  neighborhood: "Heritage Square",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Ski-in/Ski-out Chalet in Mountain Resort",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image27.jpg", "path/to/image28.jpg"],
  category: "Chalet",
  price: 3500,
  location: "Mountain Resort",
  reviews: {
    rating: 4.9,
    comments: ["Perfect location!", "Great for winter sports."],
  },
  seating: 8,
  description: "A luxurious chalet with direct access to ski slopes, ideal for a winter getaway.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1200,
  neighborhood: "Alpine Village",
  squareFeet: 2200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Elegant Mansion in Prestigious Neighborhood",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image29.jpg", "path/to/image30.jpg"],
  category: "Mansion",
  price: 8000,
  location: "Exclusive Neighborhood",
  reviews: {
    rating: 5.0,
    comments: ["Luxury at its finest!", "Exceptional service."],
  },
  seating: 12,
  description: "An exquisite mansion with lavish interiors and expansive grounds in a sought-after neighborhood.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Luxury Estates",
  squareFeet: 6000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Seaside Bungalow with Ocean Views",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image31.jpg", "path/to/image32.jpg"],
  category: "Bungalow",
  price: 2200,
  location: "Seaside",
  reviews: {
    rating: 4.7,
    comments: ["Perfect beach getaway!", "Soothing ocean sounds."],
  },
  seating: 4,
  description: "A charming bungalow with panoramic ocean views, steps away from the beach.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: true,
  impressions: 950,
  neighborhood: "Coastal Retreat",
  squareFeet: 1500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Luxury Villa in Tropical Paradise",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image33.jpg", "path/to/image34.jpg"],
  category: "Villa",
  price: 6000,
  location: "Tropical Island",
  reviews: {
    rating: 4.9,
    comments: ["Unparalleled beauty!", "Ultimate relaxation."],
  },
  seating: 10,
  description: "A lavish villa nestled in a lush tropical setting, offering unparalleled luxury and serenity.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1700,
  neighborhood: "Paradise Cove",
  squareFeet: 5000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Riverside Cabin with Fishing Dock",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image35.jpg", "path/to/image36.jpg"],
  category: "Cabin",
  price: 1700,
  location: "Riverside",
  reviews: {
    rating: 4.6,
    comments: ["Tranquil escape!", "Excellent fishing spot."],
  },
  seating: 4,
  description: "A cozy cabin nestled along a peaceful river, complete with a private fishing dock.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: true,
  impressions: 800,
  neighborhood: "Riverfront Retreat",
  squareFeet: 1300,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Modern Apartment in Tech Hub",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image37.jpg", "path/to/image38.jpg"],
  category: "Apartment",
  price: 2800,
  location: "Tech District",
  reviews: {
    rating: 4.8,
    comments: ["Convenient location!", "Sleek design."],
  },
  seating: 4,
  description: "A modern apartment in the heart of the tech district, ideal for urban professionals.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1200,
  neighborhood: "Innovation Alley",
  squareFeet: 1000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Coastal Retreat with Private Beach Access",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image39.jpg", "path/to/image40.jpg"],
  category: "Retreat",
  price: 3000,
  location: "Coast",
  reviews: {
    rating: 4.9,
    comments: ["Secluded paradise!", "Stunning sunsets."],
  },
  seating: 6,
  description: "A tranquil coastal retreat with direct access to a private beach, perfect for relaxation and rejuvenation.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1000,
  neighborhood: "Seaside Sanctuary",
  squareFeet: 2000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Scenic Mountain Lodge",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image41.jpg", "path/to/image42.jpg"],
  category: "Lodge",
  price: 2500,
  location: "Mountain Range",
  reviews: {
    rating: 4.7,
    comments: ["Spectacular views!", "Great for nature lovers."],
  },
  seating: 8,
  description: "A picturesque mountain lodge surrounded by breathtaking natural landscapes.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 900,
  neighborhood: "Alpine Haven",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Urban Chic Loft",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image43.jpg", "path/to/image44.jpg"],
  category: "Loft",
  price: 2000,
  location: "City Center",
  reviews: {
    rating: 4.6,
    comments: ["Stylish space!", "Close to nightlife."],
  },
  seating: 4,
  description: "An urban loft with chic design elements and easy access to city attractions.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1100,
  neighborhood: "Downtown Loft District",
  squareFeet: 1200,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Tranquil Forest Retreat",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image45.jpg", "path/to/image46.jpg"],
  category: "Retreat",
  price: 1800,
  location: "Forest",
  reviews: {
    rating: 4.8,
    comments: ["Peaceful sanctuary!", "Great for meditation."],
  },
  seating: 6,
  description: "A serene forest retreat surrounded by towering trees and natural beauty.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: true,
  impressions: 800,
  neighborhood: "Forest Haven",
  squareFeet: 1500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Historic Mansion with Garden",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image47.jpg", "path/to/image48.jpg"],
  category: "Mansion",
  price: 5000,
  location: "Historic District",
  reviews: {
    rating: 4.9,
    comments: ["Grandeur and elegance!", "Beautifully landscaped gardens."],
  },
  seating: 12,
  description: "A grand historic mansion with meticulously manicured gardens, perfect for elegant gatherings.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Heritage Estates",
  squareFeet: 6000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Luxurious Beachfront Condo",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image49.jpg", "path/to/image50.jpg"],
  category: "Condo",
  price: 3500,
  location: "Beachfront",
  reviews: {
    rating: 4.9,
    comments: ["Unbeatable ocean views!", "Upscale amenities."],
  },
  seating: 6,
  description: "A luxurious condo right on the beach with breathtaking ocean views and high-end amenities.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1300,
  neighborhood: "Oceanfront Oasis",
  squareFeet: 2000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Cozy Cottage in Countryside",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image51.jpg", "path/to/image52.jpg"],
  category: "Cottage",
  price: 1500,
  location: "Countryside",
  reviews: {
    rating: 4.7,
    comments: ["Quaint and charming!", "Peaceful surroundings."],
  },
  seating: 4,
  description: "A cozy cottage nestled in the picturesque countryside, offering tranquility and relaxation.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 900,
  neighborhood: "Rural Retreat",
  squareFeet: 1200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Chic City Apartment with Rooftop Terrace",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image53.jpg", "path/to/image54.jpg"],
  category: "Apartment",
  price: 2800,
  location: "City Center",
  reviews: {
    rating: 4.8,
    comments: ["Stunning views!", "Perfect for entertaining."],
  },
  seating: 4,
  description: "A chic city apartment with a spacious rooftop terrace boasting stunning skyline views.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1000,
  neighborhood: "Metropolitan Plaza",
  squareFeet: 1500,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Serenity Lake House",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image55.jpg", "path/to/image56.jpg"],
  category: "House",
  price: 2800,
  location: "Lakefront",
  reviews: {
    rating: 4.9,
    comments: ["Tranquil retreat!", "Idyllic lake views."],
  },
  seating: 8,
  description: "A serene lake house with stunning views, perfect for unwinding and enjoying nature.",
  term: "Long term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1200,
  neighborhood: "Lakeside Haven",
  squareFeet: 2200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Tranquil Mountain Retreat",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image57.jpg", "path/to/image58.jpg"],
  category: "Retreat",
  price: 2000,
  location: "Mountain",
  reviews: {
    rating: 4.8,
    comments: ["Peaceful getaway!", "Breath-taking views."],
  },
  seating: 6,
  description: "A tranquil retreat nestled in the mountains, offering serene surroundings and scenic beauty.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: true,
  impressions: 900,
  neighborhood: "Mountain Vista",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Charming Vineyard Cottage",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image59.jpg", "path/to/image60.jpg"],
  category: "Cottage",
  price: 2500,
  location: "Vineyard",
  reviews: {
    rating: 4.7,
    comments: ["Idyllic setting!", "Great wine tasting."],
  },
  seating: 4,
  description: "A charming cottage nestled in the midst of a picturesque vineyard, perfect for wine enthusiasts.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 1000,
  neighborhood: "Vineyard Valley",
  squareFeet: 1500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Contemporary Urban Loft",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image61.jpg", "path/to/image62.jpg"],
  category: "Loft",
  price: 3000,
  location: "City Center",
  reviews: {
    rating: 4.9,
    comments: ["Stylish and spacious!", "Great for city living."],
  },
  seating: 6,
  description: "A contemporary loft apartment in the heart of the city, featuring modern design and ample space.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1100,
  neighborhood: "Downtown Loft District",
  squareFeet: 2000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Secluded Forest Cabin",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image63.jpg", "path/to/image64.jpg"],
  category: "Cabin",
  price: 1800,
  location: "Forest",
  reviews: {
    rating: 4.6,
    comments: ["Escape to nature!", "Peaceful and remote."],
  },
  seating: 4,
  description: "A secluded cabin tucked away in the forest, offering privacy and tranquility amidst nature.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 800,
  neighborhood: "Woodland Retreat",
  squareFeet: 1200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Luxury Lakeside Villa",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image65.jpg", "path/to/image66.jpg"],
  category: "Villa",
  price: 5000,
  location: "Lakefront",
  reviews: {
    rating: 4.9,
    comments: ["Exquisite property!", "Stunning lake views."],
  },
  seating: 10,
  description: "A luxurious villa situated on the shores of a tranquil lake, offering unparalleled luxury and serenity.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Lakeside Estates",
  squareFeet: 3500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Picturesque Countryside Farmhouse",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image67.jpg", "path/to/image68.jpg"],
  category: "Farmhouse",
  price: 2200,
  location: "Countryside",
  reviews: {
    rating: 4.7,
    comments: ["Quaint and charming!", "Great for a family vacation."],
  },
  seating: 6,
  description: "A picturesque farmhouse surrounded by rolling fields and peaceful countryside.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: true,
  impressions: 1000,
  neighborhood: "Rural Retreat",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Historic Colonial Estate",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image69.jpg", "path/to/image70.jpg"],
  category: "Estate",
  price: 6000,
  location: "Historic District",
  reviews: {
    rating: 4.9,
    comments: ["Timeless elegance!", "Impeccably maintained."],
  },
  seating: 14,
  description: "A grand colonial estate with historic charm and luxurious amenities, perfect for elegant gatherings.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1800,
  neighborhood: "Heritage Estates",
  squareFeet: 8000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Oceanfront Retreat with Private Beach",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image71.jpg", "path/to/image72.jpg"],
  category: "Retreat",
  price: 3200,
  location: "Oceanfront",
  reviews: {
    rating: 4.8,
    comments: ["Paradise found!", "Soothing sounds of the waves."],
  },
  seating: 8,
  description: "An idyllic oceanfront retreat with direct access to a private beach, offering unparalleled relaxation.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1200,
  neighborhood: "Seaside Sanctuary",
  squareFeet: 2500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Rustic Log Cabin in the Woods",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image73.jpg", "path/to/image74.jpg"],
  category: "Cabin",
  price: 1800,
  location: "Wooded Area",
  reviews: {
    rating: 4.6,
    comments: ["Escape to nature!", "Cozy and inviting."],
  },
  seating: 4,
  description: "A rustic log cabin nestled in the peaceful woods, offering a cozy retreat amidst nature.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 900,
  neighborhood: "Forest Hideaway",
  squareFeet: 1400,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Luxury Desert Oasis",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image75.jpg", "path/to/image76.jpg"],
  category: "Villa",
  price: 5000,
  location: "Desert",
  reviews: {
    rating: 4.9,
    comments: ["Spectacular setting!", "Luxurious amenities."],
  },
  seating: 10,
  description: "A luxurious villa nestled in the heart of the desert, offering unparalleled luxury and serenity.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Desert Oasis",
  squareFeet: 4000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Secluded Mountain Chalet",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image77.jpg", "path/to/image78.jpg"],
  category: "Chalet",
  price: 3000,
  location: "Mountain",
  reviews: {
    rating: 4.8,
    comments: ["Idyllic retreat!", "Spectacular mountain views."],
  },
  seating: 8,
  description: "A secluded mountain chalet surrounded by pristine wilderness, perfect for nature lovers.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1100,
  neighborhood: "Mountain Haven",
  squareFeet: 2000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Riverside Cottage with Fishing Dock",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image79.jpg", "path/to/image80.jpg"],
  category: "Cottage",
  price: 2000,
  location: "Riverside",
  reviews: {
    rating: 4.7,
    comments: ["Tranquil escape!", "Excellent fishing spot."],
  },
  seating: 6,
  description: "A charming riverside cottage with its own fishing dock, offering a peaceful getaway.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 1000,
  neighborhood: "Riverside Retreat",
  squareFeet: 1600,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "City Penthouse with Skyline Views",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image81.jpg", "path/to/image82.jpg"],
  category: "Penthouse",
  price: 5000,
  location: "City Center",
  reviews: {
    rating: 4.9,
    comments: ["Breathtaking views!", "Luxurious accommodations."],
  },
  seating: 10,
  description: "A luxurious penthouse apartment in the heart of the city, boasting panoramic skyline views.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Metropolitan Plaza",
  squareFeet: 3000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Coastal Beach House",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image83.jpg", "path/to/image84.jpg"],
  category: "House",
  price: 3500,
  location: "Beachfront",
  reviews: {
    rating: 4.9,
    comments: ["Beachfront paradise!", "Relaxing and rejuvenating."],
  },
  seating: 8,
  description: "A stunning beachfront house with direct access to the sandy shores, offering the ultimate coastal getaway.",
  term: "Long term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1200,
  neighborhood: "Beachfront Bliss",
  squareFeet: 2500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Historic Townhouse with Garden",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image85.jpg", "path/to/image86.jpg"],
  category: "Townhouse",
  price: 3800,
  location: "Historic District",
  reviews: {
    rating: 4.8,
    comments: ["Quintessential charm!", "Beautifully landscaped garden."],
  },
  seating: 6,
  description: "A historic townhouse with elegant interiors and a lush garden oasis in the heart of the historic district.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1300,
  neighborhood: "Heritage Square",
  squareFeet: 2200,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Sunny Vineyard Villa",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image87.jpg", "path/to/image88.jpg"],
  category: "Villa",
  price: 4000,
  location: "Vineyard",
  reviews: {
    rating: 4.9,
    comments: ["Idyllic wine country retreat!", "Spectacular vineyard views."],
  },
  seating: 10,
  description: "A sunny villa nestled amidst rolling vineyards, offering a serene escape in wine country.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: false,
  impressions: 1400,
  neighborhood: "Vineyard Vista",
  squareFeet: 2800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Modern Lakeside Retreat",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image89.jpg", "path/to/image90.jpg"],
  category: "Retreat",
  price: 3200,
  location: "Lakefront",
  reviews: {
    rating: 4.8,
    comments: ["Contemporary elegance!", "Serenity by the lake."],
  },
  seating: 8,
  description: "A modern retreat nestled along the tranquil shores of a pristine lake, offering contemporary luxury.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1100,
  neighborhood: "Lakeview Retreat",
  squareFeet: 2200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Ski-In/Ski-Out Chalet",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image91.jpg", "path/to/image92.jpg"],
  category: "Chalet",
  price: 3500,
  location: "Ski Resort",
  reviews: {
    rating: 4.9,
    comments: ["Ultimate ski getaway!", "Convenient slope access."],
  },
  seating: 10,
  description: "A luxurious chalet with direct ski-in/ski-out access, perfect for winter sports enthusiasts.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1200,
  neighborhood: "SlopeSide Chalets",
  squareFeet: 2500,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Peaceful Lakeside Cabin",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image93.jpg", "path/to/image94.jpg"],
  category: "Cabin",
  price: 2500,
  location: "Lakefront",
  reviews: {
    rating: 4.7,
    comments: ["Tranquility by the lake!", "Cozy and inviting."],
  },
  seating: 6,
  description: "A peaceful cabin nestled by the lake, offering serene views and a cozy atmosphere.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 1000,
  neighborhood: "Lakeview Haven",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Luxury Safari Lodge",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image95.jpg", "path/to/image96.jpg"],
  category: "Lodge",
  price: 6000,
  location: "Safari Park",
  reviews: {
    rating: 4.9,
    comments: ["Exotic adventure!", "Luxury amidst the wilderness."],
  },
  seating: 12,
  description: "A luxurious safari lodge offering unparalleled comfort and adventure in the heart of the wilderness.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Safari Sanctuary",
  squareFeet: 4000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Mountain View Cabin",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image97.jpg", "path/to/image98.jpg"],
  category: "Cabin",
  price: 2800,
  location: "Mountain",
  reviews: {
    rating: 4.8,
    comments: ["Scenic retreat!", "Cozy atmosphere."],
  },
  seating: 6,
  description: "A charming cabin with panoramic mountain views, providing a peaceful escape in nature.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: true,
  impressions: 1200,
  neighborhood: "Mountain Ridge",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Rustic Farmhouse with Vineyard Views",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image99.jpg", "path/to/image100.jpg"],
  category: "Farmhouse",
  price: 3200,
  location: "Countryside",
  reviews: {
    rating: 4.9,
    comments: ["Charming countryside escape!", "Idyllic vineyard setting."],
  },
  seating: 8,
  description: "A rustic farmhouse surrounded by vineyards, offering picturesque views and country charm.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 1300,
  neighborhood: "Vineyard Valley",
  squareFeet: 2200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Luxury Ski Chalet",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image101.jpg", "path/to/image102.jpg"],
  category: "Chalet",
  price: 4500,
  location: "Ski Resort",
  reviews: {
    rating: 4.9,
    comments: ["Ski-in/ski-out luxury!", "Breathtaking mountain views."],
  },
  seating: 10,
  description: "A luxurious ski chalet with direct access to the slopes, offering unparalleled comfort and convenience.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1400,
  neighborhood: "SlopeSide Chalets",
  squareFeet: 2800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Elegant Waterfront Mansion",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image103.jpg", "path/to/image104.jpg"],
  category: "Mansion",
  price: 8000,
  location: "Waterfront",
  reviews: {
    rating: 4.9,
    comments: ["Grandeur and luxury!", "Sweeping waterfront views."],
  },
  seating: 16,
  description: "An elegant mansion nestled along the waterfront, boasting luxurious amenities and stunning views.",
  term: "Long term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1800,
  neighborhood: "Waterfront Estates",
  squareFeet: 10000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Modern City Loft with River Views",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image105.jpg", "path/to/image106.jpg"],
  category: "Loft",
  price: 3500,
  location: "City Center",
  reviews: {
    rating: 4.8,
    comments: ["Stylish urban living!", "Spectacular riverfront vistas."],
  },
  seating: 6,
  description: "A modern loft apartment in the city center, offering stylish living spaces and scenic river views.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1300,
  neighborhood: "Riverside Plaza",
  squareFeet: 2000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Tranquil Forest Cabin Retreat",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image107.jpg", "path/to/image108.jpg"],
  category: "Cabin",
  price: 2500,
  location: "Forest",
  reviews: {
    rating: 4.7,
    comments: ["Secluded forest getaway!", "Perfect for nature lovers."],
  },
  seating: 6,
  description: "A tranquil cabin retreat nestled in the forest, providing a serene escape amidst nature's beauty.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 1100,
  neighborhood: "Forest Retreat",
  squareFeet: 1800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Coastal Retreat with Private Pier",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image109.jpg", "path/to/image110.jpg"],
  category: "Retreat",
  price: 3800,
  location: "Coastline",
  reviews: {
    rating: 4.9,
    comments: ["Oceanfront paradise!", "Private pier for sunset views."],
  },
  seating: 8,
  description: "A coastal retreat with a private pier overlooking the ocean, offering a serene escape by the sea.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1500,
  neighborhood: "Coastal Haven",
  squareFeet: 2400,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Historic Manor House",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image111.jpg", "path/to/image112.jpg"],
  category: "Manor",
  price: 6000,
  location: "Historic District",
  reviews: {
    rating: 4.9,
    comments: ["Timeless elegance!", "Majestic architecture."],
  },
  seating: 12,
  description: "A historic manor house with grand architecture and elegant interiors, steeped in old-world charm.",
  term: "Long term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1600,
  neighborhood: "Heritage Estates",
  squareFeet: 6000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Serenity by the Lake",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image113.jpg", "path/to/image114.jpg"],
  category: "House",
  price: 4500,
  location: "Lakefront",
  reviews: {
    rating: 4.8,
    comments: ["Tranquil lakeside retreat!", "Perfect for family vacations."],
  },
  seating: 10,
  description: "A serene lakeside house with panoramic views of the water, offering a peaceful escape from city life.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1400,
  neighborhood: "Lakeview Estates",
  squareFeet: 2800,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Seaside Villa with Infinity Pool",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image115.jpg", "path/to/image116.jpg"],
  category: "Villa",
  price: 7000,
  location: "Seaside",
  reviews: {
    rating: 4.9,
    comments: ["Luxury by the sea!", "Infinity pool with ocean views."],
  },
  seating: 12,
  description: "A luxurious seaside villa with an infinity pool overlooking the ocean, offering unparalleled luxury.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1800,
  neighborhood: "Seaside Sanctuary",
  squareFeet: 4000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Spectacular Mountain Lodge",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image117.jpg", "path/to/image118.jpg"],
  category: "Lodge",
  price: 5500,
  location: "Mountain",
  reviews: {
    rating: 4.9,
    comments: ["Mountain paradise!", "Rustic charm with modern amenities."],
  },
  seating: 14,
  description: "A spectacular mountain lodge offering rustic charm and modern amenities amidst breathtaking scenery.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1700,
  neighborhood: "Mountain Vista",
  squareFeet: 5000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Peaceful Riverside Retreat",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image119.jpg", "path/to/image120.jpg"],
  category: "Retreat",
  price: 3000,
  location: "Riverside",
  reviews: {
    rating: 4.8,
    comments: ["Tranquility by the river!", "Ideal for nature enthusiasts."],
  },
  seating: 8,
  description: "A peaceful retreat nestled along the riverside, offering serene views and a tranquil atmosphere.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 1300,
  neighborhood: "Riverside Haven",
  squareFeet: 2200,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Luxury Golf Course Estate",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image121.jpg", "path/to/image122.jpg"],
  category: "Estate",
  price: 8500,
  location: "Golf Course",
  reviews: {
    rating: 4.9,
    comments: ["Golf enthusiast's dream!", "Opulent amenities."],
  },
  seating: 16,
  description: "A luxurious estate overlooking the golf course, offering opulent amenities and unparalleled comfort.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1900,
  neighborhood: "Fairway Estates",
  squareFeet: 6000,
  hasParking: true,
  hasPublicTransportation: true,
},
{
  title: "Tranquil Forest Retreat",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image123.jpg", "path/to/image124.jpg"],
  category: "Retreat",
  price: 2800,
  location: "Forest",
  reviews: {
    rating: 4.7,
    comments: ["Escape to nature!", "Peaceful and rejuvenating."],
  },
  seating: 8,
  description: "A tranquil retreat nestled in the forest, offering a serene escape amidst towering trees and fresh air.",
  term: "Long term",
  availability: "Upcoming",
  isSmokingAllowed: true,
  impressions: 1400,
  neighborhood: "Forest Retreat",
  squareFeet: 2000,
  hasParking: true,
  hasPublicTransportation: false,
},
{
  title: "Secluded Desert Oasis",
  owner: "609c58d74f4e123456789abc",
  picturePath: ["path/to/image125.jpg", "path/to/image126.jpg"],
  category: "Oasis",
  price: 4500,
  location: "Desert",
  reviews: {
    rating: 4.8,
    comments: ["Tranquility in the desert!", "Stargazing paradise."],
  },
  seating: 10,
  description: "A secluded oasis in the desert, offering peace and serenity under the vast desert sky.",
  term: "Short term",
  availability: "Available now",
  isSmokingAllowed: false,
  impressions: 1600,
  neighborhood: "Desert Oasis",
  squareFeet: 3000,
  hasParking: true,
  hasPublicTransportation: false,
}
];